config/routes.rb
Rails.application.routes.draw do
  
  root to: 'calculator#show'
  get '/calculator/show', to: 'calculator#show', as: 'show'
  get '/calculator/clear', to: 'calculator#clear', as: 'clear'
  get '/calculator/operator/:op', to: 'calculator#operator', as: 'operator'
  get '/calculator/number/:num', to: 'calculator#number', as: 'number'
  get '/calculator/eval', to: 'calculator#eval', as: 'eval'
  
  
end

app/models/calc.rb
class Calc

  attr_accessor :result
  
  def initialize
    @operator = ''
    @firstNumber = 0
    @secondNumber = 0
    @flag_op = false
    @result = "0"
  end
  
  def clear
    initialize
  end
  
  # Display int number without the .0 at the end
  # ==== Attributes 
  # +number+ - The number to display 
  def display(number)
    number % 1 == 0 ? number.to_i.to_s : number.to_s
  end
  
  # Add the new num (digit) to the actual number
  # Depending if the actual number is whole or not, add the digit before or after the coma
  # ==== Attributes 
  # +number+ - The number to add the new char (digit)
  # +num+ - The char to add at the end of the number
  def add(number, num)
    number % 1 == 0 ? (number.to_i.to_s + num).to_f : (number.to_s + num).to_f
  end

  # Store operator entered by the user
  # If an operator was already entered by the user before, then first eval 
  # and after add the operator with the result obtained
  # ==== Attributes 
  # +op+ - The operation entered by the user
  def operator(op)
    if @flag_op
      eval
      operator(op)
    else
      @flag_op = true
      @operator = op
      @result += op
    end
  end
  
  def number(num)
    if !@flag_op
      @firstNumber = add(@firstNumber, num)
      @result = display(@firstNumber)
    else
      @secondNumber = add(@secondNumber, num)
      @result = display(@firstNumber) + @operator + display(@secondNumber)
    end
  end
  
  def eval
    case @operator
      when '+'
        @firstNumber = @firstNumber + @secondNumber
      when '-'
         @firstNumber = @firstNumber - @secondNumber
      when 'x'
         @firstNumber = @firstNumber * @secondNumber
      when '÷'
         @firstNumber = @firstNumber / @secondNumber
      else
        # If no operator was entered or no second member of the operation to do, then display the first member
        @firstNumber = @firstNumber
    end
    @result = display(@firstNumber)
    @secondNumber = 0
    @flag_op = false
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/calculator_controller.rb
class CalculatorController < ApplicationController
  
def show
  @@calc = Calc.new()
  @result = @@calc.result
end

def clear
  @@calc.clear
  renderView
end

def operator
    @@calc.operator(params[:op])
    renderView
end

def number
    @@calc.number(params[:num])
    renderView
end

def eval
  @@calc.eval
  renderView
end

def renderView
    @result = @@calc.result
    render "calculator/show"
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calculator_helper.rb
module CalculatorHelper
end

app/views/calculator/show.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
	<title>Calculator</title>
</head>
<body>
	<header>
		<h1><%=image_tag("logo.PNG", alt: "Logo")%>The modern times calculator...</h1>
		
	</header>
  
<div id="calculator">
	<!-- Screen -->
	 
		<div class="screen"><%= @result %></div>
	
	<div class="keys">
		<!-- operators and other keys -->
		  <%= link_to '+', operator_path('+'), class: 'operator' %>
	    <%= link_to '-', operator_path('-'), class: 'operator' %>
		  <%= link_to '÷', operator_path('÷'), class: 'operator' %>
		  <%= link_to 'x', operator_path('x'), class: 'operator' %>
		
		<% (0..9).each do |i| %>
       <%= link_to i, number_path(i)%>
    <% end %>
	
		 <%= link_to 'C', clear_path, class: 'clear'  %>
		 <%= link_to '=', eval_path, class: 'eval' %>
	</div>
</div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Calculator</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>